name: Django CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r messaging_app/requirements.txt
        pip install flake8 coverage

    - name: Lint with flake8
      run: |
        echo "Running flake8 for linting..."
        flake8 messaging_app --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 messaging_app --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Set up Django environment
      env:
        DATABASE_URL: mysql://test_user:test_password@localhost:3306/test_db
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Django tests with coverage
      env:
        DATABASE_URL: mysql://test_user:test_password@localhost:3306/test_db
      run: |
        coverage run --source='.' manage.py test
        coverage report
        coverage xml

    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: **/test-reports/*
